#AD.SALE PREDICTION FROM EXISTING CUSTOMER-LOGISTRIC REGRESSION



###Importing Libraries



In [2]:
import pandas as pd #useful for importing dataset
import numpy as np #useful for array

#CHOOSE DATASET FILE FROM LOCAL DIRECTORY


In [4]:
from google.colab import files
uploaded = files.upload()

Saving digitalAd-dataset.csv to digitalAd-dataset.csv


# LOAD DATASET


In [5]:
dataset = pd.read_csv('digitalAd-dataset.csv')

#SUMMARISE DATASET

In [6]:
print(dataset.shape)
print(dataset.head(5))

(29, 3)
   AGE  SALARY  STATUS
0   10   35000       0
1   30  120000       1
2   70   10000       0
3   35   22000       0
4   22  200000       1


#SEGREGATE DATASET INTO X(INPUT/INDEPENDENT VARIABLE)AND Y(OUTPUT/DEPEDENT VARIABLE)

In [7]:
X = dataset.iloc[:,:-1].values
X


array([[    10,  35000],
       [    30, 120000],
       [    70,  10000],
       [    35,  22000],
       [    22, 200000],
       [    45,  60000],
       [    33,  56000],
       [    64,  90000],
       [    45,  55000],
       [    76,  69000],
       [    24, 100000],
       [    34,  89000],
       [    13,  59000],
       [    35,  77000],
       [    34,  50000],
       [    55, 300000],
       [    46,  90000],
       [    47, 150000],
       [    49,  90000],
       [    24,  88000],
       [    21,  60000],
       [    43, 350000],
       [    45,  20000],
       [    42,  45000],
       [    55,  25000],
       [    43,  30000],
       [    23,  40000],
       [    34,  15000],
       [    41,  33000]])

In [9]:
Y = dataset.iloc[ :, -1].values
Y

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 0, 1])

#SPLITTING THE DATASET INTO TRAIN AND TEST

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y,test_size =0.25,random_state = 0)

#FEATURE SCALING
 we scale our data to make all the features contribute equally to the result    
 Fit_Transform-fit method is calculating the mean and variance of each of the   
 features present in our data
 Transform-Transform Method is transforming all the features using the respected
 mean and variance,
 we want our test data to be a completely new and a surprise set for our model

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

#TRAINING


In [14]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train, y_train)

LogisticRegression(random_state=0)

#Predicting,whether new customer with Age & Salary will Buy or Not

In [15]:
age = int(input("Enter New Customer Age: "))
sal = int(input("Enter New Customer Salary: "))
newCust = [[age,sal]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("Customer will buy")
else:
  print("Customer won't")  

Enter New Customer Age: 25
Enter New Customer Salary: 50000
[1]
Customer will buy


#Prediction for all Test Data

In [17]:
y_pred = model.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 0]
 [1 1]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]]


#Evaluating Model -CONFUSION MATRIX

In [20]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix: ")
print(cm)

print ("Accuracy of the Model: {0}%".format(accuracy_score(y_test, y_pred)*100))

Confusion Matrix: 
[[4 0]
 [1 3]]
Accuracy of the Model: 87.5%
